language: python
python:
  - "2.7"
  - "3.2"
# commands to install dependencies
install:
  - pip install -r requirements/base.txt --use-mirrors
  - pip install nose==1.2.1
  - pip install -e .
# command to run tests
script: nosetests
